--- 
- name: install jenkins_job dependencies (via apt-get)
  become: true
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - libxml2-dev
    - libxslt-dev
    - python-dev
    - gcc
    - zlib1g-dev

- name: install jenkins_job dependencies (via pip)
  pip:
    name: "{{ item }}"
  with_items:
    - lxml
    - python-jenkins