---
- name: build a Jenkins Service
  hosts: test_vagrant
  sudo: true
  remote_user: vagrant
  tasks:
    - name: Remove directory structure
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/meeting-0.0.1-SNAPSHOT.jar
        - /var/run_jar.sh
        - /var/deploy_jar.sh
    - name: Copy project jar
      copy:
        src: ./deploy_jar.sh
        dest: /var
    - name: Stop old project
      command: sh /var/deploy_jar.sh
    - name: Copy project jar
      copy:
        src: ../target/meeting-0.0.1-SNAPSHOT.jar
        dest: /var