---
- name: add repository
  apt_repository: repo='ppa:ansible/ansible'

- name: installing ansible
  apt:
    name: ansible
    update_cache: yes
    state: latest

- name: config hosts
  copy:
    src: ../../../hosts
    dest: /etc/ansible/hosts

- name: config ansible
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg