---
- name: installing ansible
  apt:
    name: ansible
    state: installed

- name: config hosts
  copy:
    src: ../../../hosts
    dest: /etc/ansible/hosts

- name: config ansible
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg