---
- name: install git
  apt:
    name: git
    update_cache: yes
- name: install maven
  sudo: yes
  apt:
    name: maven
- name: install nginx
  apt:
    name: nginx
    update_cache: yes
- name: starte nginx
  service: 
    name: nginx
    state: started