---
- name: build a Jenkins Service
  hosts: test_vagrant
  # remote_user: root
  # gather_facts: False
  sudo: true
  remote_user: vagrant
  roles:
  - role: install-java8
  - role: install-git-tomcat-nginx
  - role: setup-jenkins
  - role: jenkins-plugins
  - role: install_mysql
  - role: set-mysql-DB