---
- name: build a Jenkins Service
  hosts: test_vagrant
  # remote_user: root
  # gather_facts: False
  sudo: true
  remote_user: vagrant
  roles:
  - role: install-git
  - role: install-java8
  - role: setup-jenkins
  - role: jenkins-plugins