---
- name: install mysql-server
  apt: 
    name: mysql-server
    state: installed

- name: install mysql-client
  apt:
    name: mysql-client
    state: installed
    
- name: install python-mysqldb
  apt:
    name: python-mysqldb
    state: installed

- name: copy bookdb.sql
  copy:
    src: ./tmp/bookdb.sql
    dest: /tmp/bookdb.sql

# - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
#   mysql_db:
#     state: import
#     login_password: "default"
#     name: all
#     target: /tmp/bookdb.sql