---
- name: Set Jenkins JAVA_ARGS
  lineinfile:
    dest: /etc/default/jenkins
    insertbefore: "^JENKINS_ARGS.*"
    line: "JAVA_ARGS=\"-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false\""
  register: jenkins_defaults

- name: Remove initial Jenkins password
  file: name=/var/lib/jenkins/secrets/initialAdminPassword state=absent

- name: Create Jenkins admin password hash
  shell: echo -n "{{ jenkins_admin_password }}{ansible_jenkins}" | sha256sum - | awk '{ print $1; }'
  register: jenkins_password_hash

- name: Create admin user directory
  file: path="~jenkins/users/admin" owner=jenkins group=jenkins mode=0755 state=directory recurse=yes

- name: Create admin
  template: src=admin-config.xml.j2 dest="~jenkins/users/admin/config.xml" force=no
  register: jenkins_admin_config

- name: set jenkins service up
  service: 
    name: jenkins
    state: started