---

- name: Adding Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Selecting Java8 Licience
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: installing Java8
  become: true
  apt:
    name: oracle-java8-installer
    state: latest
    
- name: configuring java to default
  apt:
    name: oracle-java8-set-default
    state: installed